export default {
  index: 'Master Implementations',
  tasks: 'Implementation Tasks',
  changelog: 'Changelog',
  'tech-stack': 'Tech Stack',
  'project-setup': 'Project Setup',
  'module-structure': 'Module Structure',
  database: 'Database',
  authentication: 'Authentication',
  authorization: 'Authorization',
  graphql: 'GraphQL',
  'api-workflow': 'API Workflow',
  'collection-schemas': 'Collection Schemas',
  'event-system': 'Event System',
  'worker-services': 'Worker Services',
  'file-storage': 'File Storage',
  'pdf-generation': 'PDF Generation',
  email: 'Email',
  'push-notifications': 'Push Notifications',
  testing: 'Testing',
  deployment: 'Deployment',
  versioning: 'Versioning',
  'environment-config': 'Environment Config',
  modules: 'Module Implementations'
}
