# Leads Management

> Covers: Lead capture (manual, webhook, selfie analysis), lead assignment configuration, CRM actions, status pipeline, and conversion to Patient.
> Events emitted: `LeadCreated`, `LeadConverted`
> Events consumed: none (lead creation is a source event)

---

## Glossary

- **Lead**: A prospective patient who has not yet been converted to a Patient record.
- **LeadSource**: `MANUAL` | `WEBHOOK` | `SELFIE_ANALYSIS` - see `shared/enums.md`.
- **LeadStatus**: `NEW` | `CONTACTED` | `QUALIFIED` | `CONVERTED` | `LOST` - see `shared/enums.md`.
- **LeadPriority**: `LOW` | `MEDIUM` | `HIGH` | `URGENT` - see `shared/enums.md`.
- **LeadTag**: A free-text label attached to a Lead for categorization and filtering.
- **LeadAction**: A logged interaction with a Lead including action type, optional status change, and content text.
- **WebhookSource**: An external campaign system configured to push Lead data to the platform via HTTP POST. Configured by OrganizationAdmin only.
- **FieldMapping**: A per-WebhookSource configuration that maps incoming webhook payload fields to Lead profile fields.
- **SelfieAnalysisReport**: The AI hair-loss assessment PDF generated by the Selfie Analysis web component.
- **LeadAssignmentMode**: An Organization-level setting configured by the OrganizationAdmin. Two values: `AUTO_ASSIGN` (default) and `MANUAL_ASSIGN`. Controls how incoming leads from API sources (webhook, selfie analysis) and Org Admin manual entries are assigned to clinics.
- **AUTO_ASSIGN**: The default mode. Leads are automatically assigned to the clinic determined by the source (selfie analysis selection, webhook field mapping, or Org Admin's explicit choice). Once a clinic is set, LeadDistributionAlgorithm assigns staff.
- **MANUAL_ASSIGN**: The OrganizationAdmin reviews each incoming lead. The determined clinic (from source) is shown as a suggestion only. The Org Admin must manually confirm or change the clinic assignment. Until confirmed, the lead is Unassigned. Once a clinic is assigned, LeadDistributionAlgorithm assigns staff.
- **UnassignedLead**: A Lead with `clinicId = null`. In `AUTO_ASSIGN` mode, only occurs when no clinic can be determined from the source (e.g., webhook with no clinic in payload, Org Admin manual entry with no clinic selected). In `MANUAL_ASSIGN` mode, all incoming leads start as Unassigned until the Org Admin confirms a clinic. Visible to OrganizationAdmin only.
- **LeadDistributionAlgorithm**: The pluggable mechanism by which incoming leads within a Clinic are distributed to active Staff members with lead access. The current implementation is RoundRobin (even rotation across eligible staff). The algorithm is defined as a separate, independently configurable component so it can be replaced without changing the lead assignment requirements.
- **Conversion**: The process of creating a Patient record from a Lead record, transferring applicable fields automatically.

---

## Lead Assignment Model

### AUTO_ASSIGN Mode (default)

```
Lead created
    │
    ├── Source: MANUAL by Clinic Staff
    │       └── Always assigned to Staff member's current Clinic → LeadDistributionAlgorithm assigns Staff
    │
    ├── Source: MANUAL by OrganizationAdmin
    │       ├── Clinic selected → assigned to that Clinic → LeadDistributionAlgorithm assigns Staff
    │       └── No Clinic selected → UnassignedLead
    │
    ├── Source: SELFIE_ANALYSIS
    │       ├── Single-clinic org → auto-assigned to that Clinic → LeadDistributionAlgorithm assigns Staff
    │       └── Multi-clinic org → visitor MUST select Clinic (mandatory) → LeadDistributionAlgorithm assigns Staff
    │           (Selfie Analysis NEVER produces UnassignedLead in AUTO_ASSIGN mode)
    │
    └── Source: WEBHOOK
            ├── Clinic in payload (via field mapping) → assigned to that Clinic → LeadDistributionAlgorithm assigns Staff
            └── No Clinic in payload → UnassignedLead
```

### MANUAL_ASSIGN Mode

```
Lead created
    │
    ├── Source: MANUAL by Clinic Staff
    │       └── Always assigned to Staff member's current Clinic → LeadDistributionAlgorithm assigns Staff
    │           (Clinic Staff manual leads are NOT affected by MANUAL_ASSIGN mode)
    │
    ├── Source: MANUAL by OrganizationAdmin
    │       └── Clinic shown as suggestion (if determinable) → Org Admin confirms/changes → LeadDistributionAlgorithm assigns Staff
    │           (If Org Admin does not confirm → UnassignedLead)
    │
    ├── Source: SELFIE_ANALYSIS
    │       └── Visitor-selected Clinic shown as suggestion to Org Admin → Org Admin confirms/changes → LeadDistributionAlgorithm assigns Staff
    │           (Until Org Admin confirms → UnassignedLead)
    │
    └── Source: WEBHOOK
            └── Clinic from payload shown as suggestion to Org Admin → Org Admin confirms/changes → LeadDistributionAlgorithm assigns Staff
                (Until Org Admin confirms → UnassignedLead)
```

### Common Rules (both modes)

- **Clinic Staff manual leads** are always assigned to their own Clinic regardless of mode.
- **Once a Clinic is assigned**, LeadDistributionAlgorithm distributes the lead to an active Staff member with lead access. ClinicAdmin is the fallback if no other eligible staff exists.
- **Invariant:** For any Lead L where `L.clinicId` is non-null, `L.assignedStaffId` MUST also be non-null.
- **Mode changes** affect only future leads. Existing leads are not retroactively reassigned.

---

## Lead Visibility Model

| Role | Sees |
|------|------|
| Any Clinic Staff (with lead access) | All leads in their Clinic, regardless of `assignedStaffId` |
| ClinicAdmin | All leads in their Clinic, regardless of `assignedStaffId` |
| OrganizationAdmin | All leads across all Clinics + UnassignedLeads (`clinicId = null`) |

> **Note:** Per-staff lead visibility (staff seeing only their own assigned leads) is deferred to a future iteration.

---

## Requirements

### LM-1: Lead Assignment Mode Configuration

**User Story:** As an OrganizationAdmin, I want to configure how incoming leads are assigned to clinics so that I can control whether assignment is automatic or requires my review.

#### Acceptance Criteria

1. THE Platform SHALL provide an Organization-level `leadAssignmentMode` setting with two values: `AUTO_ASSIGN` and `MANUAL_ASSIGN`.
2. THE default value SHALL be `AUTO_ASSIGN`.
3. THE Platform SHALL allow OrganizationAdmins to change `leadAssignmentMode` at any time.
4. WHEN `leadAssignmentMode` is changed, THE Platform SHALL apply the new mode to all future leads only. Existing leads are not affected.
5. `leadAssignmentMode` applies to leads from: webhook sources, selfie analysis, and manual entries by OrganizationAdmin.
6. `leadAssignmentMode` does NOT apply to manual leads created by Clinic-level Staff - those are always assigned to the Staff member's current Clinic.
7. WHEN `leadAssignmentMode` is changed, THE Platform SHALL record the change in the AuditLog.

#### Correctness Properties

- For any Lead L created after a mode change, L SHALL follow the assignment rules of the new mode.
- For any Lead L created before a mode change, L's assignment SHALL remain unchanged.

---

### LM-2: Lead Profile

**User Story:** As a Staff member with lead create permission, I want to create and manage lead profiles so that the clinic can track all prospective patients in one place.

#### Acceptance Criteria

1. THE Platform SHALL store the following fields for each Lead: `firstName`, `lastName`, `age`, `genderAssignedAtBirth`, `email`, `phone`, `createdAt`, `status`, `priority`, `tags[]`, `leadSource`, `sourceDetail` (page URL or campaign ID), `clinicId` (nullable for unassigned leads), `assignedStaffId` (nullable).
2. THE Platform SHALL allow duplicate Leads - the same email or phone MAY exist across multiple Lead records.
3. THE Platform SHALL allow Staff to update `status`, `priority`, and `tags` at any time.
4. WHEN a Lead is created via the SelfieAnalysis web component, THE Platform SHALL attach the selfie analysis questions, answers, and `selfieAnalysisReport` to the Lead profile. `selfieAnalysisReport` may be null if image capture failed or questions were incomplete - the Lead is still created and assigned.
5. WHEN a Lead is created, THE Platform SHALL set the initial `status` to `NEW`.
6. WHEN a Lead is created, THE Platform SHALL emit a `LeadCreated` event.
7. WHEN a Lead is created, THE Platform SHALL record the action in the AuditLog.
8. Any Clinic Staff member with lead access SHALL see all leads belonging to their Clinic (`clinicId` matches their Clinic), regardless of which staff member is assigned.
9. OrganizationAdmins SHALL see all Leads across all Clinics within their Organization, including UnassignedLeads (`clinicId = null`).
10. THE Platform SHALL allow creation of additional fields for Leads in the future if required.

#### Failure Cases

| Condition | Error Code |
|-----------|------------|
| Missing `name` field | `VALIDATION_ERROR` (field: `name`) |

#### Correctness Properties

- Two Lead records with identical email values SHALL both be creatable and retrievable without error.
- For any newly created Lead L: `L.status = NEW` immediately after creation.
- For any Clinic Staff member S in Clinic C with lead access: the Lead list query SHALL return all Leads where `clinicId = C`.
- For any OrganizationAdmin A: the Lead list query SHALL return all Leads in A's Organization including those with `clinicId = null`.
- For any Lead L where `L.clinicId` is non-null: `L.assignedStaffId` SHALL also be non-null.

---

### LM-3: Manual Lead Entry

**User Story:** As a Staff member with lead create permission, I want to manually enter lead information so that I can capture prospective patients from phone calls, walk-ins, and other offline channels.

#### Acceptance Criteria

1. THE Platform SHALL provide a `createLead` mutation for Staff to manually create a Lead.
2. At least one of `firstName` or `lastName` is required; all other fields are optional.
3. WHEN a Clinic-level Staff member creates a Lead manually, THE Platform SHALL automatically set `clinicId` to the Staff member's current Clinic and distribute the Lead via LeadDistributionAlgorithm. This is not affected by `leadAssignmentMode`.
4. WHEN an OrganizationAdmin creates a Lead manually in `AUTO_ASSIGN` mode:
   - If a Clinic is selected → `clinicId` is set and LeadDistributionAlgorithm distributes the Lead.
   - If no Clinic is selected → Lead is created as an UnassignedLead.
5. WHEN an OrganizationAdmin creates a Lead manually in `MANUAL_ASSIGN` mode:
   - A Clinic selector is shown. Any pre-filled value is a suggestion only.
   - The Org Admin must explicitly confirm a Clinic to assign it.
   - If the Org Admin does not confirm a Clinic → Lead is created as an UnassignedLead.
6. WHEN a Lead is manually created, THE Platform SHALL set `leadSource` to `MANUAL`.

#### Failure Cases

| Condition | Error Code |
|-----------|------------|
| Missing both `firstName` and `lastName` | `VALIDATION_ERROR` (field: `firstName`) |
| Unauthorized user attempting to create a lead | `FORBIDDEN` |

---

### LM-4: Webhook Lead Ingestion

**User Story:** As an OrganizationAdmin, I want to configure webhooks from external marketing campaigns so that leads are automatically captured in the platform.

#### Acceptance Criteria

1. THE Platform SHALL allow OrganizationAdmins (only) to configure one or more WebhookSources, each with a unique endpoint URL and a FieldMapping.
2. THE FieldMapping SHALL allow mapping each incoming webhook payload field to the corresponding Lead profile field, including an optional `clinicId` mapping.
3. WHEN a webhook payload is received, THE Platform SHALL parse it using the configured FieldMapping and create a Lead record. The Platform SHALL NEVER reject lead creation from a valid webhook request due to staff availability.
4. WHEN a webhook payload is received, THE Platform SHALL set `leadSource` to `WEBHOOK` and `sourceDetail` to the campaign ID from the mapped field.
5. In `AUTO_ASSIGN` mode:
   - If the payload contains a valid `clinicId` → Lead is assigned to that Clinic → LeadDistributionAlgorithm assigns Staff.
   - If no `clinicId` in payload → Lead is created as an UnassignedLead.
6. In `MANUAL_ASSIGN` mode:
   - The `clinicId` from the payload (if present) is stored as a suggestion on the Lead.
   - Lead is created as an UnassignedLead pending Org Admin confirmation.
7. IF a webhook payload is missing a required mapped field, THE Platform SHALL reject the payload, return an error response to the sender, and record the failure in the AuditLog.
8. Webhook configuration (create, edit, delete WebhookSources) is restricted to OrganizationAdmins only.

#### Failure Cases

| Condition | HTTP Status | Error Code |
|-----------|-------------|------------|
| Invalid API key | 401 | `WEBHOOK_INVALID_API_KEY` |
| Missing required mapped field | 422 | `WEBHOOK_MAPPING_ERROR` |
| Malformed JSON payload | 400 | `WEBHOOK_PAYLOAD_INVALID` |
| Webhook source not found | 404 | `NOT_FOUND` |
| ClinicAdmin attempting to configure webhooks | 403 | `FORBIDDEN` |

#### Correctness Properties

- For any webhook payload P with field mapping M, the Lead created from P SHALL have field values equal to `M(P)` for every mapped field.
- For any webhook payload P missing a required mapped field, the Lead creation SHALL fail and no Lead record SHALL be created.
- WebhookSource configuration mutations SHALL fail for any actor who is not an OrganizationAdmin.
- In `AUTO_ASSIGN` mode: a webhook lead with a valid `clinicId` SHALL have `assignedStaffId` set immediately after creation.
- In `MANUAL_ASSIGN` mode: all webhook leads SHALL be created as UnassignedLeads regardless of `clinicId` in payload.

---

### LM-5: Selfie Analysis Web Component Lead Capture

**User Story:** As a prospective patient on a clinic's website or app, I want to complete a selfie-based hair analysis and select my preferred clinic so that I receive an instant assessment and the right clinic can follow up with me.

#### Acceptance Criteria

1. THE Platform SHALL provide a SelfieAnalysis web component built with Stencil, embeddable on any Organization's website or app.
2. THE SelfieAnalysis web component is authenticated using the Organization's API key. There are no clinic-level API keys.
3. WHEN a visitor starts the SelfieAnalysis flow and the Organization has more than one active Clinic, THE Platform SHALL display a list of active Clinics for the visitor to select their preferred Clinic. Clinic selection is mandatory - the visitor cannot complete the flow without selecting a Clinic.
4. WHEN the Organization has exactly one active Clinic, THE Platform SHALL skip the clinic selection screen and auto-assign the lead to that Clinic.
5. WHEN a visitor completes the SelfieAnalysis flow, THE Platform SHALL capture: `firstName`, `lastName`, `age`, `genderAssignedAtBirth`, `email`, `phone`. All fields except at least one of `firstName`/`lastName` and `genderAssignedAtBirth` are optional.
6. THE Platform SHALL generate a `selfieAnalysisReport` and attach it to the Lead. The report may be null if image capture failed or questions were incomplete - the Lead is still created and assigned regardless.
7. In `AUTO_ASSIGN` mode: the Lead is immediately assigned to the visitor-selected (or auto-assigned) Clinic and distributed via LeadDistributionAlgorithm assigns Staff.
8. In `MANUAL_ASSIGN` mode: the visitor-selected Clinic is stored as a suggestion. The Lead is created as an UnassignedLead pending Org Admin confirmation.
9. WHEN the `selfieAnalysisReport` is generated, THE Platform SHALL offer the visitor the option to book an appointment via the Appointment Booking web component.
10. Setup and configuration of the SelfieAnalysis web component and its API key are restricted to OrganizationAdmins only.

#### Failure Cases

| Condition | Error Code |
|-----------|------------|
| Invalid or missing Organization API key | `WEBHOOK_INVALID_API_KEY` |
| Missing required visitor fields | `VALIDATION_ERROR` |
| Multi-clinic org: visitor attempts to complete flow without selecting a Clinic | `VALIDATION_ERROR` (field: `clinicId`) |

#### Correctness Properties

- In `AUTO_ASSIGN` mode with a multi-clinic org: the visitor SHALL select a Clinic before completing the flow. The Lead SHALL be created with `clinicId` set to the selected Clinic and `assignedStaffId` set via LeadDistributionAlgorithm.
- In `AUTO_ASSIGN` mode with a single-clinic org: the Lead SHALL be automatically assigned to that Clinic and `assignedStaffId` set via LeadDistributionAlgorithm.
- In `MANUAL_ASSIGN` mode: all Selfie Analysis leads SHALL be created as UnassignedLeads with the visitor-selected Clinic stored as a suggestion.
- For any Lead L created via SelfieAnalysis: `L.selfieAnalysisReport` may be null. The Lead is still created and assigned regardless.
- The Clinic list displayed to the visitor SHALL only include active Clinics belonging to the Organization.

---

### LM-6: Lead Assignment and Staff Distribution

**User Story:** As a ClinicAdmin, I want leads to be automatically distributed to my staff and to be able to reassign leads when needed so that no lead goes unattended.

#### Acceptance Criteria

1. WHEN a Lead is assigned to a Clinic (at creation in `AUTO_ASSIGN` mode, or by Org Admin confirmation in `MANUAL_ASSIGN` mode), THE Platform SHALL automatically assign the Lead to an active Staff member with lead access in that Clinic using LeadDistributionAlgorithm.
2. THE LeadDistributionAlgorithm SHALL cycle through all active Staff members with lead access in the Clinic in a consistent order, distributing leads evenly.
3. THE Platform SHALL NEVER reject lead creation from API sources (webhook, selfie analysis) due to staff availability. If no other eligible Staff member is found, the Lead SHALL be assigned to the ClinicAdmin as the fallback assignee.
4. WHEN an OrganizationAdmin assigns a Clinic to an UnassignedLead, THE Platform SHALL trigger LeadDistributionAlgorithm within that Clinic.
5. THE Platform SHALL allow a ClinicAdmin or Staff member with reassign permission to manually reassign a Lead to another active Staff member within the same Clinic, provided the Lead's status is `NEW` or `LOST`.
6. THE Platform SHALL NOT allow regular Staff to reassign Leads in `CONTACTED`, `QUALIFIED`, or `CONVERTED` status.
7. WHEN a Lead is reassigned, THE Platform SHALL record the change in the AuditLog including the previous and new assignee.

#### Failure Cases

| Condition | Error Code |
|-----------|------------|
| Reassigning a Lead not in `NEW` or `LOST` status (by non-admin) | `INVALID_LEAD_REASSIGNMENT` |
| Recipient Staff member is inactive | `RECIPIENT_INACTIVE` |
| Recipient Staff member belongs to a different Clinic | `FORBIDDEN` |
| Unauthorized user attempting manual lead creation | `FORBIDDEN` |

#### Correctness Properties

- For any Lead L assigned to Clinic C, `L.assignedStaffId` SHALL reference an active Staff member in Clinic C with lead access.
- The LeadDistributionAlgorithm SHALL distribute leads evenly across eligible Staff members over time. The current implementation is RoundRobin. The algorithm is pluggable and can be replaced independently.
- After reassignment, `L.assignedStaffId` SHALL reference the new assignee and the AuditLog SHALL record the previous assignee.

---

### LM-7: Unassigned Lead Management

**User Story:** As an OrganizationAdmin, I want to view and assign unassigned leads to clinics so that no lead is lost due to missing clinic assignment.

#### Acceptance Criteria

1. THE Platform SHALL allow OrganizationAdmins to view all UnassignedLeads across the Organization.
2. THE Platform SHALL allow OrganizationAdmins to assign a Clinic to any UnassignedLead. In `MANUAL_ASSIGN` mode, the suggested Clinic (if present) is pre-filled but editable.
3. WHEN a Clinic is assigned to an UnassignedLead, THE Platform SHALL trigger LeadDistributionAlgorithm within that Clinic.
4. Clinic-level Staff SHALL NOT see UnassignedLeads.
5. WHEN an UnassignedLead is assigned a Clinic, THE Platform SHALL record the change in the AuditLog.

#### Failure Cases

| Condition | Error Code |
|-----------|------------|
| Clinic-level Staff attempting to view UnassignedLeads | `FORBIDDEN` |
| Assigning a Clinic from a different Organization | `FORBIDDEN` |

#### Correctness Properties

- For any UnassignedLead L, L SHALL NOT appear in any Clinic-level Staff member's lead list.
- After a Clinic is assigned to L, `L.clinicId` SHALL be non-null and `L.assignedStaffId` SHALL be set via LeadDistributionAlgorithm.

---

### LM-8: Lead Actions and Notes

**User Story:** As a Staff member with lead edit permission, I want to log interactions against a lead so that the team has a complete history of all communications.

#### Acceptance Criteria

1. THE Platform SHALL allow Staff to add LeadActions to a Lead record, each with: `actionType` (from dropdown), optional `statusChange`, and `content` text.
2. THE Platform SHALL support the following `actionType` values: `WHATSAPP`, `EMAIL`, `FACEBOOK_MESSAGE`, `PHONE_CALL`, `IN_PERSON_MEETING`, `OTHER`.
3. WHEN a LeadAction is added, THE Platform SHALL record: `actionType`, `content`, `timestamp` (UTC), and the Staff member who added it.
4. THE Platform SHALL display all LeadActions for a Lead in reverse chronological order (newest first).
5. THE Platform SHALL preserve all LeadActions on the Lead record permanently. They are not deleted upon conversion.
6. WHEN a Lead is converted to a Patient, THE Platform SHALL link the Patient record to the originating Lead record so that LeadActions remain accessible via the Patient's history. LeadActions are referenced, not copied - no data is duplicated.
7. WHEN a LeadAction is added, THE Platform SHALL record the action in the AuditLog.

#### Failure Cases

| Condition | Error Code |
|-----------|------------|
| Invalid `actionType` value | `VALIDATION_ERROR` (field: `actionType`) |
| Lead not found | `LEAD_NOT_FOUND` |

#### Correctness Properties

- For any two LeadActions A1 and A2 on the same Lead where `A1.timestamp > A2.timestamp`, A1 SHALL appear before A2 in the list (newest first).
- For any Lead L converted to Patient P, all LeadActions on L SHALL remain accessible via P's linked lead reference. No LeadAction data is duplicated or moved.

---

### LM-9: Lead Status and Priority Management

**User Story:** As a Staff member with lead edit permission, I want to update a lead's status and priority so that the team always knows where each prospect is in the pipeline.

#### Acceptance Criteria

1. THE Platform SHALL support `LeadStatus` values: `NEW`, `CONTACTED`, `QUALIFIED`, `CONVERTED`, `LOST`.
2. Regular Staff SHALL be able to change a Lead's status to any value except `CONVERTED` (set only by the conversion process in LM-10).
3. WHEN a Lead's status is changed to `LOST`, THE Platform SHALL require explicit confirmation (`confirmed: true` in the mutation input).
4. THE Platform SHALL allow Staff to set and update `priority` and `tags`.
5. WHEN status, priority, or tags are changed, THE Platform SHALL record the change in the AuditLog.
6. THE Platform SHALL allow a ClinicAdmin or OrganizationAdmin to override a Lead's status to any value including reverting from `CONVERTED`, to correct mistakes. This override is recorded in the AuditLog with the actor's identity.

#### Failure Cases

| Condition | Error Code |
|-----------|------------|
| Regular Staff attempting to set status to `CONVERTED` manually | `INVALID_STATUS_TRANSITION` |
| Regular Staff attempting to change status of a `CONVERTED` Lead | `LEAD_ALREADY_CONVERTED` |
| Setting status to `LOST` without confirmation | `CONFIRMATION_REQUIRED` |
| Lead not found | `LEAD_NOT_FOUND` |

#### Correctness Properties

- Regular Staff SHALL NOT be able to set `L.status = CONVERTED` directly.
- ClinicAdmin and OrganizationAdmin MAY set `L.status` to any value including reverting from `CONVERTED`. The change SHALL be recorded in the AuditLog.

---

### LM-10: Lead Conversion to Patient

**User Story:** As a Staff member with lead convert permission, I want to convert a qualified lead to a patient so that the clinic can begin formal treatment without re-entering their information.

#### Acceptance Criteria

1. THE Platform SHALL allow Staff to convert a Lead to a Patient from the Lead profile page via a `convertLeadToPatient` mutation.
2. WHEN a Lead is converted, THE Platform SHALL auto-populate the Patient profile fields from the Lead's data.
3. WHEN a Lead is converted, THE Platform SHALL set the Lead's status to `CONVERTED`.
4. IF the Lead's `email` already exists as a Patient's `email` in the same Clinic, THE Platform SHALL block the conversion.
5. IF the Lead's `phone` already exists as a Patient's `phone` in the same Clinic, THE Platform SHALL block the conversion.
6. WHEN a Lead is successfully converted, THE Platform SHALL emit a `LeadConverted` event and record the conversion in the AuditLog including the resulting Patient ID.
7. WHEN a Lead is converted, THE Platform SHALL link the Patient record to the originating Lead so that LeadActions and the `selfieAnalysisReport` (if present) remain accessible via the Patient's history. No data is copied or moved.

#### Failure Cases

| Condition | Error Code |
|-----------|------------|
| Lead's email matches existing Patient email | `CONVERSION_DUPLICATE_EMAIL` |
| Lead's phone matches existing Patient phone | `CONVERSION_DUPLICATE_PHONE` |
| Lead already converted | `LEAD_ALREADY_CONVERTED` |
| Lead not found | `LEAD_NOT_FOUND` |

#### Correctness Properties

- For any Lead L converted to Patient P: every field present in L that maps to a Patient field SHALL be present and equal in P immediately after conversion.
- For any Lead L where `L.email` matches an existing Patient's email in the same Clinic: conversion SHALL fail and no Patient record SHALL be created.
- After conversion via LM-10: `L.status = CONVERTED`. Admin override via LM-9 AC-6 may revert this.

---

### LM-11: Lead Appointment Booking

**User Story:** As a Staff member with appointment create permission, I want to book an appointment directly from a lead's profile so that I can schedule consultations without switching modules.

#### Acceptance Criteria

1. THE Platform SHALL allow Staff to initiate an appointment booking from the Lead profile page.
2. WHEN booking from a Lead profile, THE Platform SHALL pre-populate the appointment form with the Lead's name and contact details.
3. WHEN an appointment is booked for a Lead, THE Platform SHALL send an email notification to the Lead's email address.
4. THE Platform SHALL allow a Lead to book their own appointment via the SelfieAnalysis web component after receiving their `selfieAnalysisReport`.

#### Failure Cases

| Condition | Error Code |
|-----------|------------|
| Lead not found | `LEAD_NOT_FOUND` |
| No available slots | `SLOT_NOT_AVAILABLE` |

#### Correctness Properties

- For any appointment booked from Lead L, the appointment's contact fields SHALL equal L's corresponding fields at the time of booking.

---

### LM-12: Web Component and Webhook Configuration Access

**User Story:** As an OrganizationAdmin, I want exclusive control over web component setup and webhook configuration so that integration points are managed at the organization level.

#### Acceptance Criteria

1. THE Platform SHALL restrict the following actions to OrganizationAdmins only:
   - Creating, editing, and deleting WebhookSources and their FieldMappings
   - Generating and revoking the Organization API key used by the Selfie Analysis and Appointment Booking web components
   - Configuring the Selfie Analysis web component (embed settings, clinic list display)
   - Configuring the Appointment Booking web component (embed settings)
   - Changing the `leadAssignmentMode` setting
2. ClinicAdmins and other Clinic-level Staff SHALL NOT have access to any of the above configuration actions.
3. WHEN any of the above configurations are changed, THE Platform SHALL record the change in the AuditLog.

#### Failure Cases

| Condition | Error Code |
|-----------|------------|
| Clinic-level Staff attempting any configuration action | `FORBIDDEN` |

#### Correctness Properties

- For any configuration mutation on WebhookSources, API keys, web component settings, or `leadAssignmentMode`, the actor SHALL be an OrganizationAdmin or the mutation SHALL fail.

---

### LM-13: Lead Distribution Algorithm

> **Design note:** The LeadDistributionAlgorithm is intentionally defined as a separate, pluggable component. Its assignment logic can be updated independently without changing the lead capture flow, assignment mode, or any other lead requirement. New rules can be added or reordered without modifying other lead requirements.

**User Story:** As a ClinicAdmin, I want the platform to automatically assign incoming leads to the most appropriate available staff member so that leads are handled promptly and fairly.

#### Distribution Trigger

WHEN a Lead is assigned to a Clinic (at creation in `AUTO_ASSIGN` mode, or upon Org Admin confirmation in `MANUAL_ASSIGN` mode), THE Platform SHALL invoke the LeadDistributionAlgorithm to assign a Staff member to that Lead.

#### Assignment Rules (current implementation: RoundRobin)

The current implementation distributes leads evenly across eligible Staff members in rotation order. The algorithm SHALL be implemented as a separate, independently deployable service so that the distribution logic can be updated without modifying the lead capture or assignment flow.

| Priority | Rule |
|----------|------|
| 1 | Select the active Staff member with lead access in the Clinic who has received the fewest leads in the current rotation cycle (RoundRobin). |
| 2 | If all eligible Staff members have equal lead counts, select the next Staff member in the defined rotation order. |
| 3 | If no eligible Staff member is found (all inactive or no lead access), assign to the ClinicAdmin as the fallback. |

#### Acceptance Criteria

1. THE LeadDistributionAlgorithm SHALL run automatically whenever a Lead is assigned to a Clinic.
2. THE assignment result SHALL be stored on the Lead record as `assignedStaffId`.
3. THE Platform SHALL allow a ClinicAdmin or Staff member with reassign permission to manually override the assigned Staff member on any Lead in `NEW` or `LOST` status.
4. WHEN the assigned Staff member is manually overridden, THE Platform SHALL record the change in the AuditLog including the previous and new assignee.
5. THE LeadDistributionAlgorithm logic SHALL be implemented as a separate, independently deployable service so that distribution rules can be updated without modifying the lead capture flow.
6. THE Platform SHALL NEVER reject lead creation from API sources (webhook, selfie analysis) due to staff availability - the ClinicAdmin is always the fallback assignee.

#### Correctness Properties

- For any Lead L assigned to Clinic C, `L.assignedStaffId` SHALL reference an active Staff member in Clinic C with lead access.
- The LeadDistributionAlgorithm SHALL distribute leads evenly across eligible Staff members over time. The current implementation is RoundRobin.
- After manual reassignment, `L.assignedStaffId` SHALL reference the new assignee and the AuditLog SHALL record the previous assignee.
- `assignedStaffId` is always set when `clinicId` is set - a clinic-scoped lead without a staff assignment is not permitted.
